=== toban/orbitstamps/src/filters/xml/schema/message.dtd
<!ELEMENT message (data, filter)>

<!ELEMENT data (callback?, signal, urgency, body)>
	<!ELEMENT body (#PCDATA)>
	<!ELEMENT urgency (#PCDATA)>
	<!ELEMENT signal (#PCDATA)>
	<!ELEMENT callback (#PCDATA)>

<!ELEMENT filter (role, room, max-delay)>
	<!ATTLIST filter timestamp CDATA #REQUIRED>
	<!ELEMENT role (#PCDATA)>
	<!ELEMENT room (#PCDATA)>
	<!ELEMENT max-delay (#PCDATA)>

=== toban/orbitstamps/bin/filters/xml/example2.xml
<?xml version="1.0"?>
<!DOCTYPE message SYSTEM "schema/message.dtd">
<message>
	<data>
		<callback>123abc</callback>
		<signal>2</signal>
		<urgency>5</urgency>
		<body>Anestesi påbörjad <room-name/></body>
	</data>
	<filter timestamp="5">
		<role>Ansv ssk ane</role>
		<room>all</room>
		<max-delay>10</max-delay>
	</filter>
</message>
